-- AlterTable
ALTER TABLE "User" ALTER COLUMN "verifyToken" SET DEFAULT '',
ALTER COLUMN "verifyTokenExpiry" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "forgotToken" SET DEFAULT '',
ALTER COLUMN "forgotTokenExpiry" SET DEFAULT CURRENT_TIMESTAMP;
